# 

stages:
  - Build
  - Unit Tests
 
nas server:
  image: ubuntu
  stage: Build
  script:
    - pwd
    - apt-get update
    - apt-get install nfs-kernel-server -y
    - mkdir -p /export/users
    - mount --bind /home/users /export/users
    - echo "/home/users    /export/users    none    bind  0  0" >> /etc/fstab
    - cat /etc/fstab | grep "/home/users"

  artifacts:
    paths:
    - export/users
    - /etc

