# 

stages:
  - Build
  - Unit Tests
 
nas server:
  image: ubuntu
  stage: Build
  script:
    - pwd
    - apt-get update
    - mkdir /root/my_dir
    - echo "/root/my_dir *(rw,async,insecure,no_root_squash)" >> /etc/exports
    - cat /etc/exports
  artifacts:
    paths:
    - root/my_dir
    - /etc/exports

